Added associated domains to resign script
owncloud/ios-app pull request #1028
Opened 2021-09-08 04:57 UTC by mneuwert

…n script
## Description
Resign script can now inject associated domains into the resigned application's entitlements.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

2021-09-08 04:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1028) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=1028) before we can accept your contribution.<br/><hr/>**Michael Neuwert** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=1028) it.</sub>

2021-09-08 07:44 UTC, michaelstingl commented
@NannaBarz could you test again with our test server? Then approve the PR.

2021-09-08 12:26 UTC, hosy requested changes

2021-09-08 12:26 UTC, hosy commented on enterprise/resign/resignOwncloudApp
> +ASSOCIATED_DOMAINS=$(<$PROVISIONING_DIR/$METHOD/domains.txt)
`$METHOD/` is no longer available in the current version. Please remove this part from the path.

2021-09-08 12:26 UTC, hosy commented on enterprise/resign/resignOwncloudApp
> +                        echo "Can not add more then 20 associated-domains as per apple guide lines";
Would be nice to add a colored output for that problem here, like:

`                         echo "${WARN}Can not add more then 20 associated-domains as per apple guide lines${NC}";`

2021-09-08 12:29 UTC, hosy requested changes

2021-09-08 12:29 UTC, hosy commented on enterprise/resign/resignOwncloudApp
In line 10 the version number needs to be increased:

`VERSION="1.2.0"`

2021-09-08 13:56 UTC, hosy commented
@mneuwert I already fixed the requested CR changes and fixed some problems.
@NannaBarz the current version of the script should now work to add associated domains putting a text file `domains.txt` in the `resign` folder. Every domain name should be in a new line.

2021-09-08 14:27 UTC, hosy commented
@NannaBarz please add a review to this PR, if you tested the new resigning script.

2021-09-10 09:39 UTC, michaelstingl approved these changes
Damken Cloud App opened, so the script worked 👍

2021-09-10 09:39 UTC, merged