[feature/rename-accounts] Rename Account without Authentication Flow
owncloud/ios-app pull request #1097
Opened 2022-01-31 09:08 UTC by hosy

## Description
Check if only the account name was changed in edit mode: save and dismiss without re-authentication

## Related Issue
#972 

## Motivation and Context
Easier account editing, without annoying the user with re-authentication

## How Has This Been Tested?
- Edit existing account
- Change name
- Tap on `Continue`
- View should be dismissed without authentication flow
- Try again with changing the URL or only changing the URL
- Authentication should now happen

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

2022-02-01 16:45 UTC, felix-schwarz requested changes

2022-02-01 16:45 UTC, felix-schwarz commented on ownCloud/Bookmarks/BookmarkViewController.swift
> +					self.userActionCompletionHandler = nil
This sending between threads and completion handlers carries the risk of `userActionCompletionHandler` being called more than once if the user if the user taps the Continue button in quick succession.

The previous version protected against this by putting `self.userActionCompletionHandler` into a variable, then setting it to `nil` - and only then sending off the block to the main thread.

Here's what I'd suggest:
```swift
	func completeAndDismiss(with hudCompletion: @escaping (((() -> Void)?) -> Void)) {
		guard let userActionCompletionHandler = self.userActionCompletionHandler else {
			return
		}

		self.userActionCompletionHandler = nil

		OnMainThread {
			hudCompletion({
				OnMainThread {
					userActionCompletionHandler(self.bookmark, true)
				}
				self.presentingViewController?.dismiss(animated: true, completion: nil)
			})
		}
	}
```

2022-02-02 20:25 UTC, felix-schwarz approved these changes

2022-02-03 11:56 UTC, jesmrec commented
### (1)

I got this one:

1. Edit account (basic auth)
2. In edit view, change name and then, enter incorrect credentials 
3. Click on `Continue`

Current: No error displayed. When list of files is opened, the `Authorization failed` dialog raises up

Expected:  (only an idea) when clicking on `Continue`, credentials checked in case they were filled up. If no credentials typed,  only name saved. 

iPhoneXR v15.3, iPadAir v14.8
`b2d3f3ff`

2022-02-03 11:57 UTC, jesmrec commented
### (2)

Probably related with (1)

In the `Edit account` view for basic auth:

Current: username is missing and editable.
Before: username was set and not editable.

Is this behaviour change expected?

iPhoneXR v15.3, iPadAir v14.8
`b2d3f3ff`

2022-02-03 12:08 UTC, jesmrec commented
### (3)

With browser authentication (OAuth2, OIDC) it's not posible to re-authenticate if the name changes. As defined above, URL has to change (i guess URLs does not use to change) to trigger the authentication flow. That means:

1. Credentials change in server
2. Edit Login (OAuth2) in app
3. Change name

Current: `Continue` changes the name but does not trigger the auth flow. As the credentials changed (this is the main reason to do an edit), the flow should be triggered.
Expected: Authentication flow triggered regardless name changes (am i right?)

For me it's not clear the expectation for this corner case in which both name and credentials are modified at the time. 

iPhoneXR v15.3, iPadAir v14.8
`b2d3f3ff`

2022-02-18 15:16 UTC, hosy commented
@jesmrec (1), (2), (3) are fixed:

- show UI to delete authentication data in edit mode (please test, with one or more accounts configured, context menu, swipe action, edit table view action, if delete authentication UI appears)
- only proceed without authentication, if authentication data is not nil

2022-02-21 13:10 UTC, jesmrec commented
@hosy 

(1) and (2) are fixed

(3) -> the way to re-authenticate with OAuth2 is with `Delete Authentication Data` right? otherwise, only the name changes. Please, confirm this is correct.

2022-02-21 14:41 UTC, hosy commented
@jesmrec yes, this is correct.

2022-02-22 08:17 UTC, jesmrec commented
Tested with two accounts together (Basic & OAuth2). Checks done:

- [X] Edit action in swipe - Change name
- [X] Edit action in swipe - Delete & Change authentication data - Enter correct credentials
- [X] Edit action in swipe - Delete & Change authentication data - Enter bad credentials
- [X] Edit action in swipe - Delete & Change authentication data + Change name
- [X] Edit action in swipe - Change nothing
- [X] Edit action in contextual - Change name
- [X] Edit action in contextual - Delete & Change authentication data - Enter correct credentials
- [X] Edit action in contextual - Delete & Change authentication data - Enter bad credentials
- [X] Edit action in contextual - Delete & Change authentication data + Change name
- [X] Edit action in contextual - Change nothing
- [X] Add new account with name
- [X] Add new account without name

2022-02-22 08:20 UTC, jesmrec commented
Functional tests has passed and feature works as expected. 

But, the re-authentication flow has changed and now authentication data must be cleaned. This is something new and maybe users don't expect that behaviour and try to authenticate by using the `Save` button as before. 

Should we include a tip about editing credentials just below the `Delete Authentication Data`? something like:

`Please, before typing new credentials delete old ones. "Save" button will only save the bookmark name`

2022-02-22 08:23 UTC, jesmrec commented
For me this is approved!

2022-02-22 08:23 UTC, jesmrec approved these changes

2022-02-22 08:26 UTC, merged