[fix/token-timetolerance] Retry requests that failed with a 401 during a token refresh
owncloud/ios-app pull request #1105
Opened 2022-03-10 20:25 UTC by felix-schwarz

## Description
Re-schedules/Retries requests that were:
- sent before a token refresh AND
- ended after a token refresh AND
- then failed with a 401 status code
using the latest token.

Different tokens are identified by comparing the `OCAuthenticationDataID` of the authentication data used when authorizing the request with the latest `OCAuthenticationDataID` of the bookmark.

## Related Issue
https://github.com/owncloud/enterprise/issues/5059

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-03-10 20:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=1105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=1105) it.</sub>

2022-03-14 11:53 UTC, hosy requested changes

2022-03-14 11:53 UTC, hosy commented on ownCloud.xcodeproj/project.pbxproj
> +				APP_VERSION = 210;
Versioning should be removed, because it will be also merged into the `milestone/11.9.0`

2022-03-14 11:53 UTC, hosy commented on ownCloud.xcodeproj/project.pbxproj
> +				APP_VERSION = 210;
Versioning should be removed, because it will be also merged into the `milestone/11.9.0`

2022-03-14 11:53 UTC, hosy commented
@felix-schwarz please set the correct merge branch

2022-03-21 09:44 UTC, felix-schwarz commented
Merged as part of SDK changes into `11.9.0`.

2022-03-21 09:44 UTC, closed without merging