[fix/share-extension-passcode-lock-interval] Share Extension Passcode Lock Interval
owncloud/ios-app pull request #1156
Opened 2022-09-20 11:21 UTC by hosy

## Description
Passcode lock interval will now respected in share extension

## Related Issue
#1154

## Motivation and Context
Working passcode lock interval in share extension.

## How Has This Been Tested?
Have a look at the issue

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Added changelog files for the fixed issues in folder changelog/unreleased

2022-09-20 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1156) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=1156) before we can accept your contribution.<br/><hr/>**Matthias Hühne** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=1156) it.</sub>

2022-09-20 13:16 UTC, jesmrec commented
### (1)

If mote than one account in device, after choosing account i get a blurry screen:

https://user-images.githubusercontent.com/14894746/191265676-9b513269-811d-44d7-968c-07571cb3a7e0.MP4

iPhoneXR iOS15
iPhone13 iOS16

`97bdce1e`

2022-09-20 14:42 UTC, felix-schwarz requested changes
I still need to wrap my head around the code changes as a whole, but this code finding jumped out to me. And with a finding from @jesmrec open, I thought I'd share this right away and then do another round once @jesmrec's finding is fixed.

2022-09-20 14:42 UTC, felix-schwarz commented on ownCloud Share Extension/ShareViewController.swift
> +        super.viewWillAppear(animated)
`viewWill_Disappear_()` calls `super.viewWill_Appear_()` here. That should probably be `super.viewWill_Disappear_()`

2022-09-21 08:17 UTC, hosy commented
@jesmrec your QA finding should be fixed now.
@felix-schwarz CR finding is fixed too!

2022-09-21 09:07 UTC, jesmrec commented
Fixed!

2022-09-21 09:07 UTC, jesmrec approved these changes

2022-09-21 15:07 UTC, felix-schwarz approved these changes

2022-09-21 20:55 UTC, merged