[feature/v12-onboarding] New Branded Onboarding
owncloud/ios-app pull request #1208
Opened 2023-04-27 09:43 UTC by hosy

## Description
Migrated the branded onboarding process into the vanilla add account view.
Adding accounts will be handled in the same view.

As an addition if no account was added, an onboarding view will be shown.

## Motivation and Context
Add accounts to the app and remove old branded onboarding.

## How Has This Been Tested?
- try vanilla onboarding
- try onboarding with customer file `Branding.plist`

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- x ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

2023-04-27 09:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=1208) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: hosy<br/>:x: felix-schwarz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=1208) it.</sub>

2023-05-02 07:47 UTC, felix-schwarz requested changes

2023-05-02 07:47 UTC, felix-schwarz commented on ownCloud/App Controllers/AppRootViewController.swift
> +                messageView.elements?.append(.button(addAccountTitle, action: UIAction(handler: { [weak self] action in
The buttons could also be included directly in the array passed to `.infoBox(additionalElements:)`.

2023-05-02 07:47 UTC, felix-schwarz commented on ownCloudAppShared/UIKit Extension/UIImage+Extension.swift
> +    public func withRoundedCorners(radius: CGFloat? = nil) -> UIImage? {
This method doesn't seem to be used anywhere.

2023-05-03 14:18 UTC, hosy commented on ownCloud/App Controllers/AppRootViewController.swift
> +                messageView.backgroundView?.cssSelector = .info
Please can you show me an example of setting up a new css selector?

2023-05-03 14:19 UTC, hosy commented
@felix-schwarz fixed CR findings and left a comment.

2023-05-04 09:20 UTC, felix-schwarz commented
@hosy I added the CSS selector and added records for them in this commit:
https://github.com/owncloud/ios-app/pull/1208/commits/294ee5ce306f2cba4076289674fbff987d4438bc

2023-05-04 09:24 UTC, felix-schwarz approved these changes

2023-05-05 07:37 UTC, hosy commented
@jesmrec do you want to have a look before merging?

2023-05-05 08:47 UTC, jesmrec commented
i will, yes

2023-05-09 11:43 UTC, jesmrec commented
about the first screen. Is that intended such black frame around the ownCloud blue? 

| iPhone | iPad |
| :-: | :-: |
|![Screen Shot 2023-05-09 at 13 38 53](https://github.com/owncloud/ios-app/assets/14894746/da41e867-c7f1-4ab7-9dee-42eff4f7c57b)|![Screen Shot 2023-05-09 at 13 37 10](https://github.com/owncloud/ios-app/assets/14894746/8f46f74c-44f1-4ea2-bf26-bc01cf81dca4)|

2023-05-15 08:44 UTC, jesmrec approved these changes

2023-05-15 08:53 UTC, merged

2023-05-22 10:55 UTC, felix-schwarz commented
Merged into https://github.com/owncloud/ios-app/pull/1095.