[translation-sync] Translation sync
owncloud/ios-app pull request #1250
Opened 2023-07-12 12:28 UTC by hosy

## Description
Get the latest translation into the current milestone

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

2023-07-12 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1250) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=1250) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: ownclouders<br/>:white_check_mark: hosy<br/>:x: Matthias Hühne<br/>:x: felix-schwarz<br/><hr/>**Matthias Hühne** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=1250) it.</sub>

2023-07-20 19:40 UTC, felix-schwarz requested changes
I found a couple of issues in this PR:
- it contains source code changes (mostly bringing back source code files removed entirely in v12)
- at least the German translation would overwrite currently existing translations with their untranslated English strings. Example:
![Bildschirmfoto 2023-07-20 um 21 38 12](https://github.com/owncloud/ios-app/assets/639669/b0b0ccb5-45d1-441b-abd7-a00b805b841c)

2023-08-03 08:09 UTC, felix-schwarz approved these changes

2023-08-03 08:10 UTC, jesmrec approved these changes

2023-08-07 12:53 UTC, merged