[feature/feedback]
owncloud/ios-app pull request #1366
Opened 2024-06-28 10:20 UTC by felix-schwarz

## Description
- new view providing an overview of help and support options with a brief textual description, adding the forums to the mix
- for non-branded apps Settings make this view available as "Help & Support", replacing "Documentation", "Help" and "Feedback"

## Related Issue
https://github.com/owncloud/enterprise/issues/6594

## Screenshots (if appropriate):
"Help & Support" in Settings | Overview
---|---
<img width="283" alt="Bildschirmfoto 2024-06-28 um 12 19 38" src="https://github.com/owncloud/ios-app/assets/639669/c67408e0-99db-4b87-99c9-687bfe58bd70"> | <img width="283" alt="Bildschirmfoto 2024-06-28 um 12 19 41" src="https://github.com/owncloud/ios-app/assets/639669/6f8430f9-d611-4acc-a602-37e4a6c4fbf5">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-06-28 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=1366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=1366) it.</sub>

2024-07-03 12:16 UTC, hosy requested changes

2024-07-03 12:16 UTC, hosy commented on ownCloud/Client/HelpAndSupportViewController.swift
> +				.button("Send feedback".localized, action: UIAction(handler: { _ in
Would make sense to use `[weak self]`

2024-07-16 07:54 UTC, felix-schwarz commented on ownCloud/Client/HelpAndSupportViewController.swift
> +				.button("Send feedback".localized, action: UIAction(handler: { _ in
Fixed. Thanks!

2024-07-16 08:35 UTC, hosy approved these changes

2024-07-19 12:35 UTC, jesmrec commented
> for non-branded apps Settings make this view available as "Help & Contact", replacing "Documentation", "Help" and "Feedback"

Which is the expected behaviour for branded apps?  customers who use to have their own email address for managing their own feedback, might be interested in keeping that flow.

I did the following test:  i added to `Branding.plist`: 

```
<dict>
        ...
	<key>branding.send-feedback-address</key>
	<string>test@test.com</string>
        ...
</dict>
```

the `Help & Contact` from vanilla app splits in 3 sections up (the ones existing before):

<img width="324" alt="Screenshot 2024-07-19 at 14 28 03" src="https://github.com/user-attachments/assets/96135181-7bea-4a67-bbbf-b913324f2873">

`Documentation` and `Help` point to (branded) URLs, but `Send Feedback` prompts to the survey. Shouldn't it keep the branded email address?

Don't forget that the survey names the `ownCloud iOS app`, that is static, non-brandable and unreachable for us. Customers shouldn't read that.

As reference, that was the implemented behaviour in the Android app, if helps:

https://github.com/owncloud/enterprise/issues/6594#issuecomment-2196818498

2024-07-23 14:28 UTC, felix-schwarz commented
@jesmrec Thanks for catching this. That was a bug:
- previously there was a default value for the feedback email, but not for the feedback URL
- now it's vice versa
- therefore, when the feedback URL was set, that was preferred
- now with the default value, the URL was always used unless explicitly setting it to an empty value

The solution then was to prefer the email address now - now that it no longer has a default value. That issue is fixed with the latest commit.

2024-07-23 15:48 UTC, jesmrec commented
> The solution then was to prefer the email address now - now that it no longer has a default value. That issue is fixed with the latest commit.

that's perfect and working fine

- [X] No branding -> survey
- [X] Branding and mail -> mail
- [X] Branding and no mail -> survey

2024-07-23 15:48 UTC, jesmrec commented
Approved on my side

2024-07-23 15:49 UTC, jesmrec approved these changes

2024-07-24 12:39 UTC, merged