[feature/xcstrings-transition] xcstrings transition
owncloud/ios-app pull request #1380
Opened 2024-09-06 10:26 UTC by hosy

## Description
Migrate project to XCStrings localization

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Added an issue with details about all relevant changes in the [**iOS documentation repository**](https://github.com/owncloud/docs-client-ios-app/issues).
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

2024-09-11 18:41 UTC, felix-schwarz requested changes
Additional note:
A few dozen German translations for newer functionality were lost during a previous Transifex run: https://github.com/owncloud/ios-app/commit/99a97cd7032e212597e85c6b1d0dfd9b359b21fc#diff-4bfaa1899cb23e0e9c3b6724a0372b9a9e6e0e539cc0a2bfd49b362d4a441ecd

If time permits, it would be great to see those translations brought back so they directly are exported to Transifex, too. This could be achieved by something along these lines:
```bash
# Check out last commit of this PR before conversion to xcstrings and reset the position
git checkout feature/xcstrings-transition
git reset --hard afb0ee58246ebc98050f0dd59fde2e46b4fddb91
git checkout afb0ee58246ebc98050f0dd59fde2e46b4fddb91

# Check out last complete version of de translations
git checkout ffb28aa86f347d6d34e1756e7d47cbefe23c01b0 ownCloud/Resources/de.lproj/Localizable.strings

# Commit changes
git add ownCloud/Resources/de.lproj/Localizable.strings
git commit -m "Restore previous version of German translation"

# Finally:
# 1) perform conversions to xcstrings files in Xcode
# 2) commit
# 3) force push via: git push -f origin feature/xcstrings-transition
```

2024-09-12 13:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=1380) <br/>All committers have signed the CLA.

2024-09-12 13:37 UTC, hosy commented on ownCloud/App Controllers/AppRootViewController.swift
> +			let betaAlert = ThemedAlertController(with: OCLocalizedString("Beta Warning", nil), message: OCLocalizedString("\nThis is a BETA release that may - and likely will - still contain bugs.\n\nYOU SHO
fixed

2024-09-13 10:09 UTC, felix-schwarz approved these changes
Thanks!

I added a few commits to
- also move the FileProvider and ownCloudApp framework over to xcstrings (and fix a few build MacCatalyst-target-only errors that stood in Xcode's way) 
- remove unused strings
- add missing German translations and update it

Please have a look at my commits, and if they're fine with you, too, please feel free to merge this PR.

2024-09-13 11:11 UTC, merged