[feature/fileprovider-passcode-UI] File Provider Passcode UI
owncloud/ios-app pull request #881
Opened 2021-01-28 20:10 UTC by hosy

## Description
Added a passcode UI for the file provider, when a passcode was set in the app. With this UI the file provider can be used with passcode set immediately. Passcode can be entered directly in the file provider extension.

In addition the resign script and fastlane script got an update to set all identifiers and provisioning profiles.

## Related Issue
#880 

## Motivation and Context
Secure the app with passcode set immediately and and use the file provider extension by unlocking the passcode in the extension.

## How Has This Been Tested?
- Set a passcode
- Lock application `immediately`
- Open Files.app
- Select ownCloud file provider
- Tap `Authorize`
- Passcode UI should appear and disappear after entering the correct passcode

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/736109/106192989-374d9580-61ad-11eb-97cf-22f1db43e1d9.mov

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-02-19 12:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=881) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=881) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: hosy<br/>:white_check_mark: mneuwert<br/>:x: felix-schwarz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=881) it.</sub>

2021-02-25 22:06 UTC, felix-schwarz requested changes

2021-02-26 13:12 UTC, hosy commented on ownCloud File Provider UI/DocumentActionViewController.swift
> +			label.text = "Passcode protection is not supported on this device.\nPlease disable passcode lock in the app settings.".localized
Fixed!

2021-02-26 13:12 UTC, hosy commented on ownCloud/Settings/SecuritySettingsSection.swift
> +				let frequencySection = StaticTableViewSection(headerTitle: "Lock application".localized, footerTitle: "If you choose \"Immediately\" the App will be locked, when it is no longer in foreground.".l
Fixed!

2021-02-26 13:16 UTC, hosy commented on ownCloud File Provider UI/Info.plist
> +	<string>ownCloud</string>
Fixed!

2021-02-26 13:16 UTC, hosy commented
@felix-schwarz code review findings are fixed and you can have a look again. Thanks!

2021-02-26 16:43 UTC, felix-schwarz commented
@hosy Thanks for making the changes!

I noticed that now the passcode view in the Files.app now read `ownCloud File Provider UI` and went looking in the Info.plists for the other extensions to see how we solved it there. I then saw that `ownCloud` was hardcoded there and remember that we had similar issues in the past in those other targets, because `PRODUCT_NAME` is usually the name of the target, not `ownCloud`.

I assume the branding scripts then replace those hardcoded product names in the Info.plists, but also wondered if it's possible to define a project-wide "global" variable `APP_PRODUCT_NAME` - and use that in all Info.plists instead. 

I tried and it worked, so since I already had made the change, I committed it to fix the naming issue.

2021-02-26 16:43 UTC, felix-schwarz approved these changes

2021-03-10 07:49 UTC, jesmrec commented
QA checks

- [x] Passcode enabled -> asked in Files App
- [X] Passcode + Biometrical enabled -> asked in Files App
- [X] Passcode disabled -> not asked in Files App
- [X] Lock disabled -> Passcode asked instantly
- [ ] Lock 1 min -> Passcode after 1 min in Files App

2021-03-10 07:51 UTC, jesmrec commented
### (1)

Probably not a bug, but i want to be sure:

The passcode view that you see in Files App is always "Dark", even when you have a "Light" theme in the app. Are those views linked in some way? are they independent? is that expected?

2021-03-10 08:00 UTC, jesmrec commented
### (2)

Check these steps out:

1. In the app set a passcode
2. Enter in Files App -> Passcode is asked
3. Enter a wrong password many times

Current: You can enter the wrong passcode as many times as you want, as fast as you can. If you close Files App and open it again, you will see the Passcode view but the buttons do not work (app is locked). Nothing indicates what's going on.

Expected: Same as the app: every time you fail, you will have to wait more time to do a new attempt (as in the app). In case the app is locked after several wrong passcodes, it should be indicated to the user somehow.

iPhone XR v14.4
`27ef6c99`

2021-03-11 07:07 UTC, hosy commented
@jesmrec (1) and (2) are fixed.
(2) was a problem, which is currently also available in the share sheet in the release version.

2021-03-11 07:08 UTC, hosy commented
@jesmrec please test this on iPad too.

2021-03-12 13:10 UTC, jesmrec commented
### (3)

I have noticed the following behaviour in iPad:

1. In app, set passcode
2. Open Files App, ownCloud account
3. Passcode required, enter passcode

Current behaviour: passcode view is dismissed, ownCloud app is visible:


https://user-images.githubusercontent.com/14894746/110944280-8b1ad500-833c-11eb-939c-6345bce2d7b8.mov


Expected: When passcode view is dismissed, ownCloud app is visible

iPadAir2 v13.4
`c5fda239`

2021-03-12 13:37 UTC, hosy commented
@jesmrec please deinstall the app and reinstall it again.it looks like the extension was not loaded.you can also try to￼ force quite files.app.

2021-03-15 07:36 UTC, jesmrec commented
> @jesmrec please deinstall the app and reinstall it again.it looks like the extension was not loaded.you can also try to￼ force quite files.app.

It did not fix the problem. iPad is iOS13, could it affect?

2021-03-15 08:26 UTC, hosy commented
@jesmrec FileProvider UI deployment target was set to iOS 14.2, now the minimum iOS version is 12.1. You can check it again!

2021-03-15 10:19 UTC, jesmrec commented
(3) is fixed but ...

### (4)

with the iOS 13 iPad:

1. In app, set passcode and enable biometrical (touch/face)
2. Open Files App, ownCloud account
3. Enter touch id. 

Current: Files app is not unlocked

https://user-images.githubusercontent.com/14894746/111138419-3071bb00-8580-11eb-8be5-367978cc5296.MP4

Expected: Files app unlocked

iPadAir2 v13.4
`187e9914`

2021-03-15 15:10 UTC, hosy commented
@jesmrec good catch! Should be fixed now with commit 10f74e7

2021-03-16 08:16 UTC, jesmrec commented
### (5)

With commit `a9197e8` (sdk `29c2eb83`) , i can reproduce (3) in iPhone, after it was fixed in iPad

https://user-images.githubusercontent.com/14894746/111276734-f237d280-8637-11eb-94cb-dbc2608a8113.MP4

https://user-images.githubusercontent.com/14894746/111276721-ed731e80-8637-11eb-94e1-c00400115a03.MP4

2021-03-16 09:15 UTC, jesmrec commented
This is approved on my side

2021-03-16 09:15 UTC, jesmrec approved these changes

2021-03-16 09:28 UTC, merged