[milestone/11.6.1] Milestone 11.6.1
owncloud/ios-app pull request #978
Opened 2021-06-01 14:05 UTC by felix-schwarz

## Description
Milestone PR for version 11.6.1.

## Directly merged changes
- per-action enabled class setting is replaced with array-based `action.allowed` and `action.disallowed`, examples in the project file as runtime env options

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Added changelog files for the fixed issues in folder changelog/unreleased

2021-06-01 14:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/ios-app?pullRequest=978) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/ios-app?pullRequest=978) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: mneuwert<br/>:white_check_mark: hosy<br/>:x: felix-schwarz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/ios-app?pullRequest=978) it.</sub>

2021-06-04 09:16 UTC, michaelstingl requested changes, later dismissed
@felix-schwarz something is fishy with this PR. Looks like you're reverting plenty of stuff from @hosy . Check changes in `docs/modules/ROOT/pages/ios_mdm_tables.adoc` for example.

2021-06-07 14:16 UTC, felix-schwarz commented
@michaelstingl @hosy I created a completely new branch from `master` now, cherry-picked my changes on top and force-pushed that as `milestone/11.6.1`. Should be all cleaned up now.

2021-06-24 08:54 UTC, hosy approved these changes

2021-06-24 08:55 UTC, jesmrec approved these changes

2021-06-24 09:12 UTC, michaelstingl approved these changes
looks better now 👍

2021-06-24 11:21 UTC, merged